services:
  project-db:
    image: "mysql:5.7.43"
    container_name: projekt-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: zaq1@WSX
      MYSQL_USER: user
      MYSQL_PASSWORD: zaq1@WSX
      MYSQL_DATABASE: test
  project-app:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    image: "php_czysty"
    ports:
      - 8080:80
    volumes:
      - ./:/app
    depends_on:
      - project-db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      -  project-db
    environment:
      PMA_HOST:  project-db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
networks:
  backend:
    name: bd